---
title: Projects
---

## APCSP Final Project

For my AP Computer science principals final project, I commited myself to recreating the 1971 Star Trek video game. 
In this game, you play as the Enterprise, and navigate through an 8-by-8 grid of different quadrants in order to find and destroy Klingon ships in a certain ammount of stardates. 
Upon entering, the player is greeted with ASCII art of the enterprise, and a prompt to look at instrutions, or jump into the game. Once the player begins, a grid is generated.
The grid is randomly populated by stars, star bases, and enemy ships. Stars block the player from traveling, forcing them around, star bases allow player to utalize a turn to restore their shield, and Klingopn ships will fire at the Enterprise after your turn. 
Every turn, the player is able to select from 8 commands in order to progress; these include, warping, long and short range scans, firing torpedos and phasers, shield control, docking into starbases, and checking the libray computer.
At the end of the game, the player is given a message and can play again. 

This game was incredibly difficult to put together, as there were many intricate computations and freatures that intertwined together. As well, the information about this game was very limited, and I had to use youtube videos to decipher what was hapopening internally with each player action.


----

## The History of the War of the Ring



I am creating a comprehensive and detailed history of the conflict that goes beyond the surface-level events. By gathering information from a variety of sources, including my own memories, written accounts, and oral histories, I hope to shed new light on this important period in Middle-earth's history and provide valuable insights into the motivations and actions of the various players involved.


